### ISSUE TITLE
ImScripting fails to load

### ISSUE THREAD

**Issue by beniroquai** [ImSwitch/ImSwitch#183]
Hey @jacopoabramo, I remember you solved an issue with ImScripting not being able to start on Windows due to some weird Qscintilla version conflict. Do you remember what happened and how you resolved it in the end? @ranranking has some issues now.

**Comment by jacopoabramo** [comment]
Hey @beniroquai sorry for the late reply. I just re-installed QScintilla to be at a specific version which works. From the requirements it lists that QScintilla version should be >= 2.12. I would attempt a --force-reinstall with qscintilla==2.12 and see if it works.

**Comment by beniroquai** [comment]
Perfect! I'll keep that in mind. Thanks a lot! :-)
