### ISSUE TITLE
Create a functionality to display all the stacked images from SLM scan

### ISSUE THREAD

**Issue by Kubiczek36** [ImSwitch/ImSwitch#199]

**Comment by beniroquai** [comment]
what exactly do you mean? SLM => Single Localisation? You can always push data to a napari layer 

Just one out of many examples:
https://github.com/openUC2/ImSwitch/blob/b1540ea18ac7299c12ad69b8cb7ca615f51b0fac/imswitch/imcontrol/controller/controllers/SIMController.py#L250

**Comment by Kubiczek36** [comment]
Hi, I'm sorry but I thought that I've created this issue in our clone of the repository. Sorry for disturbing.
